//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy_MyPortfolio_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblProject
    {
        public int ProjectId { get; set; }

        [Required(ErrorMessage ="Proje Adý Boþ Geçilemez")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Proje Url Boþ Geçilemez")]
        public string ImageUrl { get; set; }

        [Required(ErrorMessage = "Proje Açýklama Boþ Geçilemez")]
        [MaxLength(250,ErrorMessage = "Açýklama bölümü en fazla 250 karakter olmalýdýr.")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Kategori Boþ Geçilemez")]
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Github Linki Boþ Geçilemez")]
        public string GithubUrl { get; set; }
    
        public virtual TblCategory TblCategory { get; set; }
    }
}
